apiVersion: v1
kind: Service
metadata:
  name:  pet-clinic-service
  namespace: observability
spec:
  #type: LoadBalancer
  selector:
    app: spring-petclinic
  ports:
    - name: http 
      protocol: TCP
      port: 8083
      targetPort: 8082