apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-k8s-conf
  labels:
    name: prometheus-k8s-conf
  namespace: observability
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
    scrape_configs:
    - job_name: 'Otel-Scrape'
      static_configs:
      - targets: ['otel-collector.observability.svc.cluster.local:9090']